### ISSUE TITLE
Add Motion2DComponent for handling velocity and acceleration in 2D entities

### ISSUE THREAD

**Issue by cdsupina** [amethyst/space_shooter_rs#28]
A Motion2DComponent will have the properties for velocity, acceleration, angular velocity, and angular acceleration. This will replace the velocity and acceleration values that are currently stored in the core components for entities.

Motion2DComponent properties:

```rust
pub struct Motion2DComponent {
    pub velocity: [f32; 2],
    pub acceleration: [f32; 2],
    pub angular_velocity: f32,
    pub angular_acceleration: f32,
}
```

**Comment by tigleym** [comment]
Helps with #29
